=== marianjanfranko/sipvs/posledneZadanie/etc/UFL.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ufl_team">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="team_name"/>
        <xs:element type="xs:string" name="email"/>
        <xs:element type="xs:integer" name="phone_number"/>
        <xs:element name="players">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="player" maxOccurs="5" minOccurs="3">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="firstname"/>
                    <xs:element type="xs:string" name="lastname"/> 
                    <xs:element type="xs:boolean" name="leaguest"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="gender" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== marianjanfranko/sipvs/posledneZadanie/etc/sample_xml.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ufl_team xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="UFL.xsd">
  <team_name>Black Coyottes</team_name>
  <email>tomas.bako@gmail.cm</email>
  <phone_number>0900111222</phone_number>
  <players>
    <player gender="m">
      <firstname>Tomas</firstname>
      <lastname>Schwartz</lastname>
      <leaguest>false</leaguest>
    </player>
    <player gender="m">
      <firstname>Peter</firstname>
      <lastname>Konecny</lastname>
      <leaguest>false</leaguest>
    </player>
    <player gender="m">
      <firstname>Michal</firstname>
      <lastname>Sevcovic</lastname>
      <leaguest>true</leaguest>
    </player>
  </players>
</ufl_team>
